maximum_availability_zones: 5

# Set to true when you want to create and
# attache a EFS mount to your ec2 ECS cluster.
# enable_ec2_cluster must be set to true
enable_efs: false

detailed_monitoring: false

iam_policies:
  loadbalancer-manage:
    action:
      - ec2:AuthorizeSecurityGroupIngress
      - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
      - elasticloadbalancing:DeregisterTargets
      - elasticloadbalancing:Describe*
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:RegisterTargets
  ec2-describe:
    action:
      - ec2:DescribeTags
      - ec2:DescribeInstances

userdata: |
  INSTANCE_ID=$(/opt/aws/bin/ec2-metadata --instance-id|/usr/bin/awk '{print $2}')
  hostname ${EnvironmentName}-ecs-${!INSTANCE_ID}
  sed '/HOSTNAME/d' /etc/sysconfig/network > /tmp/network && mv -f /tmp/network /etc/sysconfig/network && echo "HOSTNAME=${EnvironmentName}-ecs-${!INSTANCE_ID}\" >>/etc/sysconfig/network && /etc/init.d/network restart

efs_mount: |
  mkdir /efs
  yum install -y nfs-utils
  mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${FileSystem}.efs.${AWS::Region}.amazonaws.com:/ /efs

# cfnsignal: |
#   /opt/aws/bin/cfn-signal --exit-code $? \
#            --stack  ${AWS::StackName} \
#            --resource AutoScaleGroup  \
#            --region ${AWS::Region}
